runtime : python
env : flex
entrypoint : gunicorn -b :$app_final:app

runtime config:
  python version: 3
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory gb: 0.5
  disk_size_gb: 10
