runtime: python37
env: flex

handlers:
- url: /.*
  script: auto

runtime_config:
  python_version: 3

env_variables:
  AI_KEY: "AIzaSyAr5Y0PkiBcud22VdAns_MliATO-zPv9Mc"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cpu_utilization:
    target_utilization: 0.65
